{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "a8bae91d-5d5f-44fa-896f-813168c9e29a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 필요한 라이브러리 설치\n",
    "# pip install feedparser pandas streamlit schedule wordcloud matplotlib\n",
    "\n",
    "import feedparser\n",
    "import pandas as pd\n",
    "import streamlit as st\n",
    "import schedule\n",
    "import time\n",
    "from datetime import datetime\n",
    "from wordcloud import WordCloud\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "98143fc4-3335-4cbd-a425-ff57ea252a56",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 신문사 RSS 피드 목록 및 신문사 이름\n",
    "rss_feeds = {\n",
    "    \"조선일보\" : \"http://rssplus.chosun.com/\",\n",
    "    \"동아일보\" : \"http://rss.donga.com/\",\n",
    "    \"중앙일보\" : \"https://rss.joins.com/\",\n",
    "    \"매일경제\" : \"https://www.mk.co.kr/rss/\",\n",
    "    \"한국경제\" : \"http://rss.hankyung.com/\",\n",
    "    \"경항신문\" : \"http://www.khan.co.kr/help/help_rss.html\",\n",
    "    \"한겨레\" : \"http://www.hani.co.kr/arti/RSS/list1.html\",\n",
    "    \"연합뉴스\" : \"https://www.yonhapnewstv.co.kr/add/rss\",\n",
    "    \"JTBC\" : \"https://news.jtbc.joins.com/Etc/RssService.aspx\"\n",
    "    # 다른 신문사 RSS 피드 추가\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "7be5202b-697b-4610-8478-c6849e3127b7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 기사 데이터를 수집 및 처리하는 함수\n",
    "def fetch_articles():\n",
    "    articles = []\n",
    "    for source, feed_url in rss_feeds.items():\n",
    "        feed = feedparser.parse(feed_url)\n",
    "        for entry in feed.entries:\n",
    "            articles.append({\n",
    "                \"source\": source,\n",
    "                \"title\": entry.title,\n",
    "                \"link\": entry.link,\n",
    "                \"summary\": entry.summary,\n",
    "                \"published\": entry.get('published', '1970-01-01T00:00:00Z'),  # published 필드가 없을 경우 기본값 설정\n",
    "                \"category\": entry.tags[0].term if 'tags' in entry else 'Uncategorized'  # 카테고리 추가\n",
    "            })\n",
    "    df = pd.DataFrame(articles)\n",
    "    df['published'] = pd.to_datetime(df['published'])\n",
    "    return df\n",
    "\n",
    "# 키워드 분석 및 워드 클라우드 생성 함수\n",
    "def generate_wordcloud(text):\n",
    "    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)\n",
    "    plt.figure(figsize=(10, 5))\n",
    "    plt.imshow(wordcloud, interpolation='bilinear')\n",
    "    plt.axis('off')\n",
    "    st.pyplot(plt)\n",
    "\n",
    "# Streamlit 대시보드 생성 함수\n",
    "def create_dashboard(df):\n",
    "    st.title(\"한국 신문사 최신 기사 대시보드\")\n",
    "    \n",
    "    # 신문사 선택 필터\n",
    "    source_filter = st.sidebar.multiselect(\"신문사 선택\", options=df['source'].unique(), default=df['source'].unique())\n",
    "    filtered_df = df[df['source'].isin(source_filter)]\n",
    "    \n",
    "    # 날짜 선택 필터\n",
    "    start_date = st.sidebar.date_input(\"시작 날짜\", value=filtered_df['published'].min().date())\n",
    "    end_date = st.sidebar.date_input(\"종료 날짜\", value=filtered_df['published'].max().date())\n",
    "    filtered_df = filtered_df[(filtered_df['published'].dt.date >= start_date) & (filtered_df['published'].dt.date <= end_date)]\n",
    "    \n",
    "    # 카테고리 선택 필터\n",
    "    category_filter = st.sidebar.multiselect(\"카테고리 선택\", options=filtered_df['category'].unique(), default=filtered_df['category'].unique())\n",
    "    filtered_df = filtered_df[filtered_df['category'].isin(category_filter)]\n",
    "\n",
    "    # 키워드 검색 필터\n",
    "    keyword = st.sidebar.text_input(\"키워드 검색\")\n",
    "    if keyword:\n",
    "        filtered_df = filtered_df[filtered_df['title'].str.contains(keyword, case=False) | filtered_df['summary'].str.contains(keyword, case=False)]\n",
    "    \n",
    "    # 기사 데이터프레임 표시\n",
    "    st.dataframe(filtered_df)\n",
    "\n",
    "    # 기사 요약 텍스트를 하나의 문자열로 결합\n",
    "    all_summaries = ' '.join(filtered_df['summary'])\n",
    "    \n",
    "    # 워드 클라우드 생성\n",
    "    st.subheader(\"인기 키워드 분석\")\n",
    "    generate_wordcloud(all_summaries)\n",
    "\n",
    "# 초기 데이터 수집\n",
    "df = fetch_articles()\n",
    "\n",
    "# 대시보드 실행\n",
    "st.set_page_config(layout=\"wide\")\n",
    "st.write(\"실시간 업데이트 중...\")\n",
    "create_dashboard(df)\n",
    "\n",
    "# 실시간 업데이트 스케줄러\n",
    "def update_data():\n",
    "    global df\n",
    "    df = fetch_articles()\n",
    "    create_dashboard(df)\n",
    "\n",
    "# 일정 간격(10분)마다 데이터 업데이트\n",
    "schedule.every(10).minutes.do(update_data)\n",
    "\n",
    "while True:\n",
    "    schedule.run_pending()\n",
    "    time.sleep(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "81c4f5d1-d6ac-4152-8a16-f6370d0578df",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
